[project]
name = "esphome-hitachi-ac"
version = "1.0.0"
description = "ESPHome external component for controlling Hitachi AC using IRremoteESP8266 (HITACHI_AC1 protocol)"
repository = "https://github.com/yourusername/esphome-hitachi-ac"
license = "MIT"

[tool.uv.dependencies]
# Add any Python package dependencies here.
# For instance, if you need ESPHome's codegen libraries:
esphome = ">=2022.0.0"

# You might also list uv itself, although it's already installed.
